- project:
    queue: senlin
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - senlin-dsvm-tempest-py3-api
        - senlin-dsvm-tempest-py3-api-2023-1
        - senlin-dsvm-tempest-py3-api-zed
        - senlin-dsvm-tempest-py3-api-yoga
        - senlin-dsvm-tempest-py3-api-xena
        - senlin-dsvm-tempest-py3-api-wallaby
        - senlin-tempest-api-ipv6-only
        - senlin-dsvm-tempest-py3-functional
        - senlin-dsvm-tempest-py3-integration:
            voting: false
    gate:
      jobs:
        - senlin-dsvm-tempest-py3-api
        - senlin-tempest-api-ipv6-only
        - senlin-dsvm-tempest-py3-functional

- job:
    name: senlin-dsvm-tempest-py3-api-2023-1
    parent: senlin-dsvm-tempest-py3-api
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.1

- job:
    name: senlin-dsvm-tempest-py3-api-zed
    parent: senlin-dsvm-tempest-py3-api
    nodeset: openstack-single-node-focal
    override-checkout: stable/zed

- job:
    name: senlin-dsvm-tempest-py3-api-yoga
    parent: senlin-dsvm-tempest-py3-api
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga

- job:
    name: senlin-dsvm-tempest-py3-api-xena
    parent: senlin-dsvm-tempest-py3-api
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena

- job:
    name: senlin-dsvm-tempest-py3-api-wallaby
    parent: senlin-dsvm-tempest-py3-api
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby
