- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - senlin-dsvm-tempest-py3-api
        - senlin-dsvm-tempest-py3-api-xena
        - senlin-dsvm-tempest-py3-api-wallaby
        - senlin-dsvm-tempest-py3-api-victoria
        - senlin-dsvm-tempest-py3-api-ussuri
        - senlin-tempest-api-ipv6-only
        - senlin-dsvm-tempest-py3-functional
        - senlin-dsvm-tempest-py3-integration:
            voting: false
    gate:
      queue: senlin
      jobs:
        - senlin-dsvm-tempest-py3-api
        - senlin-tempest-api-ipv6-only
        - senlin-dsvm-tempest-py3-functional

- job:
    name: senlin-dsvm-tempest-py3-api-xena
    parent: senlin-dsvm-tempest-py3-api
    override-checkout: stable/xena

- job:
    name: senlin-dsvm-tempest-py3-api-wallaby
    parent: senlin-dsvm-tempest-py3-api
    override-checkout: stable/wallaby

- job:
    name: senlin-dsvm-tempest-py3-api-victoria
    parent: senlin-dsvm-tempest-py3-api
    override-checkout: stable/victoria

- job:
    name: senlin-dsvm-tempest-py3-api-ussuri
    parent: senlin-dsvm-tempest-py3-api
    override-checkout: stable/ussuri
